# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: 3.0.4
info:
  title: Service API
  description: |-
    Service API.
  version: 1.0.0

servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: "8080"

tags:
  - name: templates
    description: |-
      Templates tag

paths:

components:
